# Generated by Django 3.2.18 on 2023-03-13 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(help_text='Enter Last Name', max_length=254),
        ),
    ]
